{{-- Vista Blade de alineaciones con el PND; centraliza campos compartidos por crear y editar. --}}
@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div><x-input-label for="institutional_objective_id" value="Objetivo institucional" /><select id="institutional_objective_id" name="institutional_objective_id" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">@foreach ($institutionalObjectives as $objective)<option value="{{ $objective->id }}" @selected((string) old('institutional_objective_id', $alignment->institutional_objective_id) === (string) $objective->id)>{{ $objective->code }} - {{ $objective->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('institutional_objective_id')" class="mt-2" /></div>
    <div><x-input-label for="pnd_objective_id" value="Objetivo PND" /><select id="pnd_objective_id" name="pnd_objective_id" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">@foreach ($pndObjectives as $pndObjective)<option value="{{ $pndObjective->id }}" @selected((string) old('pnd_objective_id', $alignment->pnd_objective_id) === (string) $pndObjective->id)>{{ $pndObjective->code }} - {{ $pndObjective->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('pnd_objective_id')" class="mt-2" /></div>
    <div><x-input-label for="contribution_level" value="Nivel de contribucion" /><select id="contribution_level" name="contribution_level" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"><option value="low" @selected(old('contribution_level', $alignment->contribution_level) === 'low')>Baja</option><option value="medium" @selected(old('contribution_level', $alignment->contribution_level) === 'medium')>Media</option><option value="high" @selected(old('contribution_level', $alignment->contribution_level) === 'high')>Alta</option></select></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', $alignment->status) === $key)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="justification" value="Justificacion" /><textarea id="justification" name="justification" rows="4" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('justification', $alignment->justification) }}</textarea></div>
    <div><x-input-label for="observations" value="Observaciones" /><textarea id="observations" name="observations" rows="4" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('observations', $alignment->observations) }}</textarea></div>
</div>
<div class="mt-6 flex items-center gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('pnd-alignments.index') }}" class="text-sm text-gray-600 hover:text-gray-900">Cancelar</a></div>
