{{-- Vista Blade de proyectos de inversion y expedientes; centraliza campos compartidos por crear y editar. --}}
@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div><x-input-label for="public_entity_id" value="Entidad" /><select id="public_entity_id" name="public_entity_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="">Sin entidad</option>@foreach ($entities as $entity)<option value="{{ $entity->id }}" @selected((string) old('public_entity_id', $project->public_entity_id) === (string) $entity->id)>{{ $entity->code }} - {{ $entity->name }}</option>@endforeach</select></div>
    <div><x-input-label for="institutional_objective_id" value="Objetivo institucional" /><select id="institutional_objective_id" name="institutional_objective_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="">Sin objetivo</option>@foreach ($objectives as $objective)<option value="{{ $objective->id }}" @selected((string) old('institutional_objective_id', $project->institutional_objective_id) === (string) $objective->id)>{{ $objective->code }} - {{ $objective->name }}</option>@endforeach</select></div>
    <div><x-input-label for="code" value="Codigo" /><x-text-input id="code" name="code" class="mt-1 block w-full" value="{{ old('code', $project->code) }}" required /></div>
    <div><x-input-label for="name" value="Nombre" /><x-text-input id="name" name="name" class="mt-1 block w-full" value="{{ old('name', $project->name) }}" required /></div>
    <div><x-input-label for="intervention_type" value="Tipologia de intervencion" /><x-text-input id="intervention_type" name="intervention_type" class="mt-1 block w-full" value="{{ old('intervention_type', $project->intervention_type) }}" /></div>
    <div><x-input-label for="budget" value="Presupuesto" /><x-text-input id="budget" type="number" step="0.01" name="budget" class="mt-1 block w-full" value="{{ old('budget', $project->budget) }}" required /></div>
    <div><x-input-label for="start_date" value="Fecha inicio" /><x-text-input id="start_date" type="date" name="start_date" class="mt-1 block w-full" value="{{ old('start_date', optional($project->start_date)->format('Y-m-d')) }}" /></div>
    <div><x-input-label for="end_date" value="Fecha fin" /><x-text-input id="end_date" type="date" name="end_date" class="mt-1 block w-full" value="{{ old('end_date', optional($project->end_date)->format('Y-m-d')) }}" /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm">@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', $project->status) === $key)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="observations" value="Observaciones" /><textarea id="observations" name="observations" rows="3" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm">{{ old('observations', $project->observations) }}</textarea></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Descripcion" /><textarea id="description" name="description" rows="3" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm">{{ old('description', $project->description) }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('investment-projects.index') }}" class="text-sm text-gray-600">Cancelar</a></div>
