@php($canManageOds = Auth::user()?->hasPermission('ods.manage') ?? false)
<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 leading-tight">Alineacion con ODS</h2></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-4">
        @if (session('status')) <div class="bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded">{{ session('status') }}</div> @endif
        <div class="bg-white p-4 shadow-sm sm:rounded-lg"><form method="GET" class="grid grid-cols-1 md:grid-cols-4 gap-3"><select name="status" class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"><option value="">Todos los estados</option>@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(request('status') === $key)>{{ $label }}</option>@endforeach</select><x-primary-button>Filtrar</x-primary-button>@if ($canManageOds)<a href="{{ route('ods-alignments.create') }}" class="inline-flex items-center justify-center px-4 py-2 bg-indigo-600 rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-indigo-500">Nueva alineacion</a>@endif<a href="{{ route('sdgs.index') }}" class="inline-flex items-center justify-center px-4 py-2 border rounded-md text-xs font-semibold uppercase">Catalogo ODS</a></form></div>
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Objetivo institucional</th><th class="px-4 py-3 text-left">ODS</th><th class="px-4 py-3 text-left">Meta</th><th class="px-4 py-3 text-left">Estado</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($alignments as $alignment)<tr><td class="px-4 py-3">{{ $alignment->institutionalObjective->code }} - {{ $alignment->institutionalObjective->name }}</td><td class="px-4 py-3">ODS {{ $alignment->sdg->number }} - {{ $alignment->sdg->name }}</td><td class="px-4 py-3">{{ $alignment->target_reference ?: 'General' }}</td><td class="px-4 py-3">{{ $statuses[$alignment->status] ?? $alignment->status }}</td><td class="px-4 py-3 text-right">@if ($canManageOds)<a class="text-indigo-600" href="{{ route('ods-alignments.edit', $alignment) }}">Editar</a>@endif</td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-gray-500">No existen alineaciones ODS.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $alignments->links() }}</div></div>
    </div></div>
</x-app-layout>
