{{-- Vista Blade de indicadores; centraliza campos compartidos por crear y editar. --}}
@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div><x-input-label for="institutional_goal_id" value="Meta" /><select id="institutional_goal_id" name="institutional_goal_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="">Sin meta</option>@foreach ($goals as $goal)<option value="{{ $goal->id }}" @selected((string) old('institutional_goal_id', $indicator->institutional_goal_id) === (string) $goal->id)>{{ $goal->code }} - {{ $goal->name }}</option>@endforeach</select></div>
    <div><x-input-label for="institutional_objective_id" value="Objetivo" /><select id="institutional_objective_id" name="institutional_objective_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="">Sin objetivo</option>@foreach ($objectives as $objective)<option value="{{ $objective->id }}" @selected((string) old('institutional_objective_id', $indicator->institutional_objective_id) === (string) $objective->id)>{{ $objective->code }} - {{ $objective->name }}</option>@endforeach</select></div>
    <div><x-input-label for="code" value="Codigo" /><x-text-input id="code" name="code" class="mt-1 block w-full" value="{{ old('code', $indicator->code) }}" required /></div>
    <div><x-input-label for="name" value="Nombre" /><x-text-input id="name" name="name" class="mt-1 block w-full" value="{{ old('name', $indicator->name) }}" required /></div>
    <div><x-input-label for="unit" value="Unidad" /><x-text-input id="unit" name="unit" class="mt-1 block w-full" value="{{ old('unit', $indicator->unit) }}" required /></div>
    <div><x-input-label for="periodicity" value="Periodicidad" /><x-text-input id="periodicity" name="periodicity" class="mt-1 block w-full" value="{{ old('periodicity', $indicator->periodicity) }}" required /></div>
    <div><x-input-label for="baseline_value" value="Linea base" /><x-text-input id="baseline_value" type="number" step="0.01" name="baseline_value" class="mt-1 block w-full" value="{{ old('baseline_value', $indicator->baseline_value) }}" required /></div>
    <div><x-input-label for="target_value" value="Meta" /><x-text-input id="target_value" type="number" step="0.01" name="target_value" class="mt-1 block w-full" value="{{ old('target_value', $indicator->target_value) }}" required /></div>
    <div><x-input-label for="current_value" value="Valor actual" /><x-text-input id="current_value" type="number" step="0.01" name="current_value" class="mt-1 block w-full" value="{{ old('current_value', $indicator->current_value) }}" required /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm"><option value="active" @selected(old('status', $indicator->status) === 'active')>Activo</option><option value="inactive" @selected(old('status', $indicator->status) === 'inactive')>Inactivo</option></select></div>
    <div class="md:col-span-2"><x-input-label for="formula" value="Formula" /><textarea id="formula" name="formula" rows="3" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm">{{ old('formula', $indicator->formula) }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('indicators.index') }}" class="text-sm text-gray-600">Cancelar</a></div>
