{{-- Vista Blade de metas institucionales; lista registros, filtros y acciones principales. --}}
@php($canManageGoals = Auth::user()?->hasPermission('goals.manage') ?? false)
<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 leading-tight">Metas institucionales</h2></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-4">
        @if (session('status')) <div class="bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded">{{ session('status') }}</div> @endif
        <div class="bg-white p-4 shadow-sm sm:rounded-lg"><form method="GET" class="grid grid-cols-1 md:grid-cols-4 gap-3"><x-text-input name="q" value="{{ request('q') }}" placeholder="Buscar meta" /><x-primary-button>Filtrar</x-primary-button>@if ($canManageGoals)<a href="{{ route('goals.create') }}" class="inline-flex items-center justify-center px-4 py-2 bg-indigo-600 rounded-md font-semibold text-xs text-white uppercase tracking-widest">Nueva meta</a>@endif<a href="{{ route('indicators.index') }}" class="inline-flex items-center justify-center px-4 py-2 border rounded-md text-xs font-semibold uppercase">Indicadores</a></form></div>
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Meta</th><th class="px-4 py-3 text-left">Objetivo</th><th class="px-4 py-3 text-left">Valor</th><th class="px-4 py-3 text-left">Estado</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($goals as $goal)<tr><td class="px-4 py-3"><div class="font-medium">{{ $goal->code }} - {{ $goal->name }}</div><div class="text-gray-500">{{ $goal->period_year }} | {{ $goal->responsible }}</div></td><td class="px-4 py-3">{{ $goal->institutionalObjective->code ?? '' }}</td><td class="px-4 py-3">{{ $goal->target_value }} {{ $goal->unit }}</td><td class="px-4 py-3">{{ $goal->status }}</td><td class="px-4 py-3 text-right">@if ($canManageGoals)<a class="text-indigo-600" href="{{ route('goals.edit', $goal) }}">Editar</a>@else<span class="text-gray-400">Solo lectura</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-gray-500">No existen metas.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $goals->links() }}</div></div>
    </div></div>
</x-app-layout>
