{{-- Vista Blade de planes estrategicos; centraliza campos compartidos por crear y editar. --}}
@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div><x-input-label for="code" value="Codigo" /><x-text-input id="code" name="code" class="mt-1 block w-full" value="{{ old('code', $plan->code) }}" required /><x-input-error :messages="$errors->get('code')" class="mt-2" /></div>
    <div><x-input-label for="name" value="Nombre del plan" /><x-text-input id="name" name="name" class="mt-1 block w-full" value="{{ old('name', $plan->name) }}" required /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><x-input-label for="institution" value="Institucion" /><x-text-input id="institution" name="institution" class="mt-1 block w-full" value="{{ old('institution', $plan->institution) }}" required /><x-input-error :messages="$errors->get('institution')" class="mt-2" /></div>
    <div><x-input-label for="responsible_user_id" value="Responsable" /><select id="responsible_user_id" name="responsible_user_id" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"><option value="">Sin responsable</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) old('responsible_user_id', $plan->responsible_user_id) === (string) $user->id)>{{ $user->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('responsible_user_id')" class="mt-2" /></div>
    <div><x-input-label for="period_start" value="Anio inicio" /><x-text-input id="period_start" type="number" name="period_start" class="mt-1 block w-full" value="{{ old('period_start', $plan->period_start) }}" required /><x-input-error :messages="$errors->get('period_start')" class="mt-2" /></div>
    <div><x-input-label for="period_end" value="Anio fin" /><x-text-input id="period_end" type="number" name="period_end" class="mt-1 block w-full" value="{{ old('period_end', $plan->period_end) }}" required /><x-input-error :messages="$errors->get('period_end')" class="mt-2" /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', $plan->status) === $key)>{{ $label }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" class="mt-2" /></div>
    <div><x-input-label for="observations" value="Observaciones" /><textarea id="observations" name="observations" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('observations', $plan->observations) }}</textarea><x-input-error :messages="$errors->get('observations')" class="mt-2" /></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Descripcion" /><textarea id="description" name="description" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('description', $plan->description) }}</textarea><x-input-error :messages="$errors->get('description')" class="mt-2" /></div>
    <div><x-input-label for="objectives_text" value="Objetivos asociados, uno por linea" /><textarea id="objectives_text" name="objectives_text" rows="5" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('objectives_text', implode("\n", $plan->objectives ?? [])) }}</textarea></div>
    <div><x-input-label for="goals_text" value="Metas asociadas, una por linea" /><textarea id="goals_text" name="goals_text" rows="5" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('goals_text', implode("\n", $plan->goals ?? [])) }}</textarea></div>
</div>
<div class="mt-6 flex items-center gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('strategic-plans.index') }}" class="text-sm text-gray-600 hover:text-gray-900">Cancelar</a></div>
