{{-- Vista Blade de objetivos del PND; lista registros, filtros y acciones principales. --}}
@php($canManagePnd = Auth::user()?->hasPermission('pnd.manage') ?? false)
<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 leading-tight">Objetivos del Plan Nacional de Desarrollo</h2></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-4">
        @if (session('status')) <div class="bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded">{{ session('status') }}</div> @endif
        <div class="bg-white p-4 shadow-sm sm:rounded-lg"><form method="GET" class="grid grid-cols-1 md:grid-cols-3 gap-3"><x-text-input name="q" value="{{ request('q') }}" placeholder="Buscar PND" /><x-primary-button>Filtrar</x-primary-button>@if ($canManagePnd)<a href="{{ route('pnd-objectives.create') }}" class="inline-flex items-center justify-center px-4 py-2 bg-indigo-600 rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-indigo-500">Nuevo PND</a>@endif</form></div>
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Codigo</th><th class="px-4 py-3 text-left">Eje</th><th class="px-4 py-3 text-left">Objetivo</th><th class="px-4 py-3 text-left">Estado</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($pndObjectives as $objective)<tr><td class="px-4 py-3">{{ $objective->code }}</td><td class="px-4 py-3">{{ $objective->axis }}</td><td class="px-4 py-3"><div class="font-medium text-gray-900">{{ $objective->name }}</div><div class="text-gray-500">{{ $objective->policy }}</div></td><td class="px-4 py-3">{{ $objective->status === 'active' ? 'Activo' : 'Inactivo' }}</td><td class="px-4 py-3 text-right">@if ($canManagePnd)<a class="text-indigo-600" href="{{ route('pnd-objectives.edit', $objective) }}">Editar</a>@endif</td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-gray-500">No existen objetivos PND.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $pndObjectives->links() }}</div></div>
        <a class="text-indigo-600 text-sm" href="{{ route('pnd-alignments.index') }}">Ver matriz de alineacion PND</a>
    </div></div>
</x-app-layout>
