{{-- Vista Blade de objetivos institucionales; centraliza campos compartidos por crear y editar. --}}
@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div><x-input-label for="code" value="Codigo" /><x-text-input id="code" name="code" class="mt-1 block w-full" value="{{ old('code', $objective->code) }}" required /><x-input-error :messages="$errors->get('code')" class="mt-2" /></div>
    <div><x-input-label for="name" value="Nombre" /><x-text-input id="name" name="name" class="mt-1 block w-full" value="{{ old('name', $objective->name) }}" required /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><x-input-label for="institution" value="Institucion" /><x-text-input id="institution" name="institution" class="mt-1 block w-full" value="{{ old('institution', $objective->institution) }}" required /><x-input-error :messages="$errors->get('institution')" class="mt-2" /></div>
    <div><x-input-label for="strategic_plan_id" value="Plan estrategico" /><select id="strategic_plan_id" name="strategic_plan_id" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"><option value="">Sin plan asociado</option>@foreach ($plans as $plan)<option value="{{ $plan->id }}" @selected((string) old('strategic_plan_id', $objective->strategic_plan_id) === (string) $plan->id)>{{ $plan->code }} - {{ $plan->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('strategic_plan_id')" class="mt-2" /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', $objective->status) === $key)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="baseline" value="Linea base" /><textarea id="baseline" name="baseline" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('baseline', $objective->baseline) }}</textarea></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Descripcion" /><textarea id="description" name="description" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('description', $objective->description) }}</textarea></div>
    <div><x-input-label for="expected_result" value="Resultado esperado" /><textarea id="expected_result" name="expected_result" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('expected_result', $objective->expected_result) }}</textarea></div>
    <div><x-input-label for="observations" value="Observaciones" /><textarea id="observations" name="observations" rows="3" class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm">{{ old('observations', $objective->observations) }}</textarea></div>
</div>
<div class="mt-6 flex items-center gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('institutional-objectives.index') }}" class="text-sm text-gray-600 hover:text-gray-900">Cancelar</a></div>
